import type { PredictionReport, Sentiment } from '@/types/swarm'

const SENTIMENT_BADGE: Record<Sentiment, string> = {
  positive: 'bg-emerald-900/40 text-emerald-300 border-emerald-700/50',
  neutral: 'bg-slate-800 text-slate-300 border-slate-600',
  negative: 'bg-red-900/40 text-red-300 border-red-700/50',
}

const TOOL_ICON: Record<string, string> = {
  graph_search: '🕸️',
  sentiment_scan: '📊',
  agent_interview: '🎙️',
  panorama: '🛰️',
}

export default function PredictionReportView({ report }: { report: PredictionReport }) {
  return (
    <div className="h-full overflow-y-auto p-4">
      <div className="mx-auto max-w-3xl">
        <div className="flex flex-wrap items-center gap-3">
          <h2 className="text-xl font-bold text-slate-100">{report.title}</h2>
          <span className={`rounded-full border px-2.5 py-0.5 text-xs font-medium ${SENTIMENT_BADGE[report.overallSentiment]}`}>
            {report.overallSentiment} sentiment
          </span>
          <span className="rounded-full border border-amber-700/50 bg-amber-900/30 px-2.5 py-0.5 text-xs font-medium text-amber-300">
            risk {report.riskScore}/10
          </span>
        </div>

        {/* key predictions */}
        <div className="mt-4 rounded-xl border border-blue-800/40 bg-blue-950/30 p-4">
          <div className="mb-2 text-xs font-semibold uppercase tracking-wide text-blue-300">Key predictions</div>
          <ul className="space-y-1.5">
            {report.keyPredictions.map((p, i) => (
              <li key={i} className="flex gap-2 text-sm text-slate-200">
                <span className="text-blue-400">▸</span>
                <span>{p}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* sections */}
        <div className="mt-5 space-y-5">
          {report.sections.map((sec, i) => (
            <section key={i}>
              <h3 className="text-sm font-bold uppercase tracking-wide text-slate-300">
                {i + 1}. {sec.title}
              </h3>
              {sec.toolCalls.length > 0 && (
                <div className="mt-1.5 space-y-1">
                  {sec.toolCalls.map((tc, j) => (
                    <div key={j} className="rounded-lg border border-slate-800 bg-slate-900/60 px-2.5 py-1.5">
                      <div className="flex items-center gap-1.5 text-[11px] text-slate-400">
                        <span>{TOOL_ICON[tc.tool] ?? '🔧'}</span>
                        <span className="font-mono text-slate-500">{tc.tool}</span>
                        <span className="text-slate-600">·</span>
                        <span className="italic">{tc.query}</span>
                      </div>
                      <div className="mt-0.5 text-[11px] text-slate-400">→ {tc.result}</div>
                    </div>
                  ))}
                </div>
              )}
              <div className="mt-2 whitespace-pre-line text-sm leading-relaxed text-slate-200">{sec.content}</div>
            </section>
          ))}
        </div>

        <div className="mt-6 text-center text-[11px] text-slate-600">
          Generated by the Report Agent · {new Date(report.generatedAt).toLocaleString()}
        </div>
      </div>
    </div>
  )
}
